### ISSUE TITLE
Refactor sns_send_message to make thread safe

### ISSUE THREAD

**Issue by vincentsarago** [mapbox/watchbot-progress-py#16]
When initializing a backend we define a boto3 client 
https://github.com/mapbox/watchbot-progress-py/blob/ccab4153bd6a66c61267f808067b8f8aec96df5a/watchbot_progress/backends/dynamodb.py#L24-L26

and then when we send messages using `futures`, this client is shared by all threads. 

https://github.com/mapbox/watchbot-progress-py/blob/ccab4153bd6a66c61267f808067b8f8aec96df5a/watchbot_progress/main.py#L57-L60

As noted in http://boto3.readthedocs.io/en/latest/guide/resources.html#multithreading-multiprocessing and https://geekpete.com/blog/multithreading-boto3/ boto3 client are not thread safe and each thread should init it's own `boto3.session.Session()`

### Fix
```python
from boto3.session import Session as boto3_session

def send_message(self, message, subject, sns=sns):
    """Function wrapper to facilitate partial application"""

    if not sns:
        session = boto3_session()
        sns = session.client('sns')

    return sns.publish(
        Message=json.dumps(message),
        Subject=subject,
        TopicArn=self.topic)
```

note: this ☝️ fix could also add a `sns` option that will allow to pass a client from a top level function

cc @perrygeo

**Comment by perrygeo** [comment]
resolved in #19
